import { Template } from '@/types';

export const templates: Template[] = [
  {
    id: 'realestate-github',
    name: 'Real Estate Agent',
    description: 'Professional real estate website for Canadian agents and brokers - deployed to GitHub Pages',
    category: 'business',
    thumbnail: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop',
    features: ['Hero Image', 'Stats Counter', 'Property Listings', 'Blog Section', 'Neighborhoods', 'Client Reviews', 'Contact Form', 'AI Chatbot'],
    deployType: 'github',
    formSchema: [
      { id: 'siteName', type: 'text', label: 'Site Name (subdomain)', placeholder: 'my-realty', required: true },
      { id: 'companyName', type: 'text', label: 'Agent/Company Name', placeholder: 'John Smith Real Estate', required: true },
      { id: 'tagline', type: 'text', label: 'Tagline', placeholder: 'Your Trusted Real Estate Partner', required: true },
      { id: 'brokerageName', type: 'text', label: 'Brokerage Name', placeholder: 'Royal LePage', required: false },
      { id: 'licenseNumber', type: 'text', label: 'REALTOR® License #', placeholder: 'License Number', required: false },
      { id: 'heroImage', type: 'url', label: 'Hero Image URL', placeholder: 'https://images.unsplash.com/photo-...', required: false },
      { id: 'heroTitle', type: 'text', label: 'Hero Title', placeholder: 'Find Your Home. Move with Confidence.', required: true },
      { id: 'heroSubtitle', type: 'textarea', label: 'Hero Subtitle', placeholder: 'Expert guidance through your real estate journey', required: true },
      { id: 'homesSOLD', type: 'text', label: 'Homes Sold', placeholder: '500+', required: false },
      { id: 'yearsExp', type: 'text', label: 'Years Experience', placeholder: '15+', required: false },
      { id: 'rating', type: 'text', label: 'Rating', placeholder: '5.0', required: false },
      { id: 'teamRank', type: 'text', label: 'Team Rank', placeholder: '#1', required: false },
      { id: 'agentPhotoUrl', type: 'url', label: 'Agent Photo URL', placeholder: 'https://images.unsplash.com/photo-...', required: false },
      { id: 'neighborhood1', type: 'text', label: 'Neighborhood 1', placeholder: 'Downtown', required: false },
      { id: 'price1', type: 'text', label: 'Avg Price 1', placeholder: '$1,500,000', required: false },
      { id: 'neighborhood2', type: 'text', label: 'Neighborhood 2', placeholder: 'West Side', required: false },
      { id: 'price2', type: 'text', label: 'Avg Price 2', placeholder: '$1,200,000', required: false },
      { id: 'neighborhood3', type: 'text', label: 'Neighborhood 3', placeholder: 'North York', required: false },
      { id: 'price3', type: 'text', label: 'Avg Price 3', placeholder: '$950,000', required: false },
      { id: 'neighborhood4', type: 'text', label: 'Neighborhood 4', placeholder: 'Scarborough', required: false },
      { id: 'price4', type: 'text', label: 'Avg Price 4', placeholder: '$800,000', required: false },
      { id: 'neighborhood5', type: 'text', label: 'Neighborhood 5', placeholder: 'Etobicoke', required: false },
      { id: 'price5', type: 'text', label: 'Avg Price 5', placeholder: '$750,000', required: false },
      { id: 'neighborhood6', type: 'text', label: 'Neighborhood 6', placeholder: 'Mississauga', required: false },
      { id: 'price6', type: 'text', label: 'Avg Price 6', placeholder: '$700,000', required: false },
      { id: 'review1Name', type: 'text', label: 'Review 1 - Client Name', placeholder: 'John D.', required: false },
      { id: 'review1Text', type: 'textarea', label: 'Review 1 - Text', placeholder: 'Great experience working with them...', required: false },
      { id: 'review1Type', type: 'select', label: 'Review 1 - Property Type', options: ['House', 'Condo', 'Townhouse'], required: false },
      { id: 'review2Name', type: 'text', label: 'Review 2 - Client Name', placeholder: 'Sarah M.', required: false },
      { id: 'review2Text', type: 'textarea', label: 'Review 2 - Text', placeholder: 'Very professional and helpful...', required: false },
      { id: 'review2Type', type: 'select', label: 'Review 2 - Property Type', options: ['House', 'Condo', 'Townhouse'], required: false },
      { id: 'review3Name', type: 'text', label: 'Review 3 - Client Name', placeholder: 'Mike T.', required: false },
      { id: 'review3Text', type: 'textarea', label: 'Review 3 - Text', placeholder: 'Highly recommend...', required: false },
      { id: 'review3Type', type: 'select', label: 'Review 3 - Property Type', options: ['House', 'Condo', 'Townhouse'], required: false },
      { id: 'googleReviewsUrl', type: 'url', label: 'Google Reviews URL', placeholder: 'https://maps.app.goo.gl/...', required: false },
      { id: 'instagramHandle', type: 'text', label: 'Instagram Handle', placeholder: '@agentname', required: false },
      { id: 'email', type: 'email', label: 'Email', placeholder: 'john@example.com', required: true },
      { id: 'phone', type: 'text', label: 'Phone', placeholder: '+1 (555) 123-4567', required: true },
      { id: 'city', type: 'text', label: 'City', placeholder: 'Toronto', required: true },
      { id: 'province', type: 'select', label: 'Province', options: ['BC', 'AB', 'SK', 'MB', 'ON', 'QC', 'NB', 'NS', 'PE', 'NL'], required: true },
      { id: 'services', type: 'textarea', label: 'Services (one per line)', placeholder: 'Home Buying\nHome Selling\nInvestment Properties', required: true },
      { id: 'about', type: 'textarea', label: 'About You', placeholder: 'Tell clients about yourself and your experience...', required: true },
      { id: 'accentDark', type: 'color', label: 'Dark Accent Color', required: false },
    ],
  },
];

export const getTemplateById = (id: string): Template | undefined => {
  return templates.find(t => t.id === id);
};